'''strings-immutable(cant be changed)
methods:
1.islower(vonverts to lower)
2.isupper(converts to upper)
3.isdigit(0-9 values are digits)
4.isalnum(alphanumeric)
5.titlecase
6.swapcase(upper-lower and viceversa)
7.strip(remves leading and tail spaces)
8.replace(relaces the letter -need2 parameters)
9.split(string is coverted to list of dattype string)
10.capitalize(removes capitals in between and make 1st letter as capital)
11.isalpha(checks if string is alphabets)
12.isnumeric(checks if it is numeric or not)
13.isascii(checks if it is ascii value or not)'''
string=input()
# n=97
print(string.islower())
# print(string)
print(string.isupper())
print(string.isdigit())
print(string.isalnum())
print(string.title())
print(string.swapcase())
print(string.strip())
print(string.split())
print(string.capitalize())
print(string.replace())
print(string.isalpha())
# print(n.isacsii())